[package]
name = "ipfs"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[[bin]]
name = "ipfs"
path = "src/main.rs"

[dependencies]
byteorder = "*"
cbor = { git = "https://github.com/dvc94ch/rust-cbor", branch = "read-data-item" }
cid = { git = "https://github.com/multiformats/rust-cid", branch = "master" }
domain = { version = "0.4.1", git = "https://github.com/NLnetLabs/domain.git" }
env_logger = "*"
failure = "*"
fnv = "*"
futures-preview = { git = "https://github.com/rust-lang-nursery/futures-rs", branch = "master", features = ["io-compat"] }
libp2p = { version = "*", git = "https://github.com/libp2p/rust-libp2p", branch = "ben-legacy-mdns" }
log = "*"
multibase = "*"
multihash = "*"
parity-multiaddr = { version = "*", git = "https://github.com/libp2p/rust-libp2p", branch = "ben-legacy-mdns" }
parity-multihash = { version = "*", git = "https://github.com/libp2p/rust-libp2p", branch = "ben-legacy-mdns" }
protobuf = "2.0.2"
rand = "0.6"
rocksdb = "0.11.0"
rustc-serialize = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "0.1.16", features = ["async-await-preview"] }
xdg = "*"
warp = { version = "0.1.13", optional = true}

[features]
default = ["server"]
server = ["warp"]
